services:
  opcvpn:
    image: mawenqiandev/openconnect-head:latest
    container_name: opcvpn
    cap_add:
      - NET_ADMIN
    network_mode: "bridge"
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1080:1080"
      - "1081:1081"
    volumes:
      - ./vpn-start.sh:/vpn-start.sh
    command: ["/bin/sh", "/vpn-start.sh"] 
    env_file:
      - .env
    restart: unless-stopped